### PR TITLE
App devise PR

### PR DESCRIPTION
**Pull request by Javed-Shahbaz**
## In this milestone:

- The current_user method in ApplicationController was removed.
- The Devise was installed and set up.
- Users table was updated with email and hashed password column.
- The wireframe design for the login page was parsed.
- CSS styling was applied to the signup and the reset password page.
image
image
image

### CODE REVIEW

**Review by Lizdev-05 — CHANGES_REQUESTED** [review]
Hi @Javed-Shahbaz , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request
We have received your project submission, but it appears to be invalid. As this project is for pair programming, it is necessary for both partners to contribute. However, it seems that your coding partner did not participate in the project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Lizdev-05 — CHANGES_REQUESTED** [review]
Hi @Javed-Shahbaz , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

We have received your project submission, but it appears to be invalid. As this project is for pair programming, it is necessary for both partners to contribute. However, it seems that your coding partner did not participate in the project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Review by andersonlebon — COMMENTED** [review]
## Hi @Javed-Shahbaz 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You  have received your project submission, but it appears to be invalid. As this project is for pair programming, it is necessary for both partners to contribute. However, it seems that your coding partner did not participate in the project

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question `@andersonlebon` so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Shedrack-Sunday — CHANGES_REQUESTED** [review]
Hi @Javed-Shahbaz 
While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Invalid Code Review Request 🔴 
You have received your project submission, but it appears to be invalid. As this project is for pair programming, it is necessary for both partners to contribute. However, it seems that your coding partner did not participate in the project

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question @andersonlebon so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

**Review by rotimiazeez — APPROVED** [review]
Hi @Javed-Shahbaz & @abiola-arobieke 👏🏽, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Descriptive PR Title & Summary 💪🏽
✔️ Gitflow followed 👏🏽
✔️ Good job implementing the required change ✌🏽 
✔️ Good implementation of `Devise` 👌🏽
✔️ Great working on making an attractive UI 🎨

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me(@rotimiazeez) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
